#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

stashPop() {
  if [ "$IS_STASHABLE" != '' ]; then
    git stash pop
  fi
}

if [ "`git status --porcelain | grep -E "^.[^ ] "`" != '' ]; then
  git commit --allow-empty -nm 'Staged changes'
  git add .
  IS_STASHABLE=`git stash create`
  git reset
  if [ "$IS_STASHABLE" != '' ]; then
    git stash push -um 'NON-COMMIT FILES BACKUP'
  fi
  git reset --soft @^
fi
(
  npm run start-checks &&
  node helpers/check-no-sub-node-modules.js &&
  node helpers/eslint-helper.js &&
  npx eslint --ext js,jsx,ts,tsx --max-warnings=0 helpers .eslintrc.js &&
  npm run lint --ws &&
  npm run ts:noWatch --ws &&
  true
) || (stashPop && false)
stashPop
